### ISSUE TITLE
Direflow-cli does not work at all in Windows shell environments

### ISSUE THREAD

**Issue by Elindalyne** [Silind-Software/direflow#138]
**Describe the bug**  
Direflow CLI does not work in windows shell environments. It will crash out when renaming components

**To reproduce**  
0. Open cmd, powershell, etc.. in Windows
1. npm install -g direflow-cli
2. direflow create
4. fill out name, description, language, module
```
direflow create

? Choose a name for your Direflow Setup: test1234

? Give your Direflow Setup a description (optional)

? Which language do you want to use? JavaScript

? Do you want this to be an NPM module? No
[Error: EPERM: operation not permitted, rename 'C:\Source\test1234-component\src\direflow-components\direflow-component' -> 'C:\Source\test1234-component\src\direflow-components\test1234-component'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Source\\test1234-component\\src\\direflow-components\\direflow-component',
  dest: 'C:\\Source\\test1234-component\\src\\direflow-components\\test1234-component'
}

Unfortunately, something went wrong creating your Direflow Component
Error: Could not rename component folder
    at C:\Users\rsilver\AppData\Roaming\npm\node_modules\direflow-cli\dist\helpers\copyTemplate.js:80:40
    at FSReqCallback.oncomplete (fs.js:146:23)
```

**Expected behavior**  
Successful creation of my project 

**Package Manager:**  
To install Direflow, I used... (npm / yarn / something else)
npm 
**Screenshots**  

**Additional context**  
This is more than likely an issue with filepaths as using something that doesn't use Windows file paths such as git-bash will work correctly

**Comment by Silind** [comment]
Hi @Elindalyne 
Thank you for creating this issue.

We will investigate as soon as possible.

**Comment by Silind** [comment]
This is fixed in v. 3.4.15

**Comment by tomasdanek83** [comment]
Unfortunately this still happens in the latest version direflow-cli@3.5.1. It doesn't work even when running in Git Bash.

**Comment by JohnDeved** [comment]
@tomasdanek83 can you provide a bit more info about your development environment and the error you are getting?

**Comment by tomasdanek83** [comment]
STR and error are identical to the original ones of this issue.
I tried to run the command in several different folders. Command line running as administrator. It fails also in Git Bash.

Env: Windows 10, NodeJS v14.15.4
